version: 2

sources:
  - name: psa
    database: orcavault
    schema: psa
    tables:
      - name: events__fastqmanager_fastqlistrowstatechange
        columns:
          - name: event_id
            data_type: varchar
          - name: event_time
            data_type: varchar
          - name: orcabus_id
            data_type: varchar
          - name: status
            data_type: varchar
          - name: instrument_run_id
            data_type: varchar
          - name: library
            data_type: varchar
          - name: lane
            data_type: varchar
          - name: index
            data_type: varchar
          - name: is_valid
            data_type: varchar
          - name: readset_r1
            data_type: varchar
          - name: readset_r2
            data_type: varchar
          - name: load_datetime
            data_type: timestamptz
          - name: record_source
            data_type: varchar(255)

  - name: psa
    database: orcavault
    schema: psa
    tables:
      - name: events__sequence_run_state_change
        columns:
          - name: event_id
            data_type: varchar
          - name: event_time
            data_type: varchar
          - name: orcabus_id
            data_type: varchar
          - name: status
            data_type: varchar
          - name: instrument_run_id
            data_type: varchar
          - name: start_time
            data_type: varchar
          - name: end_time
            data_type: varchar
          - name: samplesheet_name
            data_type: varchar
          - name: load_datetime
            data_type: timestamptz
          - name: record_source
            data_type: varchar(255)

  - name: psa
    database: orcavault
    schema: psa
    tables:
      - name: events__sequence_run_library_linking_change
        columns:
          - name: event_id
            data_type: varchar
          - name: event_time
            data_type: varchar
          - name: orcabus_id
            data_type: varchar
          - name: instrument_run_id
            data_type: varchar
          - name: sequence_run_id
            data_type: varchar
          - name: timestamp
            data_type: varchar
          - name: libraries
            data_type: jsonb
          - name: load_datetime
            data_type: timestamptz
          - name: record_source
            data_type: varchar(255)
