version: 2

sources:
  - name: psa
    database: orcavault
    schema: psa
    tables:
      - name: event__fastq_list_row_state_change
        columns:
          - name: event_id
            data_type: varchar
          - name: event_time
            data_type: varchar
          - name: orcabus_id
            data_type: varchar
          - name: status
            data_type: varchar
          - name: instrument_run_id
            data_type: varchar
          - name: library
            data_type: varchar
          - name: lane
            data_type: varchar
          - name: index
            data_type: varchar
          - name: is_valid
            data_type: varchar
          - name: readset_r1
            data_type: varchar
          - name: readset_r2
            data_type: varchar
          - name: platform
            data_type: varchar
          - name: center
            data_type: varchar
          - name: read_count
            data_type: varchar
          - name: base_count_est
            data_type: varchar
          - name: readset_r1_rawmd5
            data_type: varchar
          - name: readset_r1_gzbytes
            data_type: varchar
          - name: readset_r2_rawmd5
            data_type: varchar
          - name: readset_r2_gzbytes
            data_type: varchar
          - name: qc_insert_size_estimate
            data_type: varchar
          - name: qc_raw_wgs_coverage_estimate
            data_type: varchar
          - name: qc_r1Q20_fraction
            data_type: varchar
          - name: qc_r2Q20_fraction
            data_type: varchar
          - name: qc_r1Gc_fraction
            data_type: varchar
          - name: qc_r2Gc_fraction
            data_type: varchar
          - name: qc_duplication_fraction_estimate
            data_type: varchar
          - name: load_datetime
            data_type: timestamptz
          - name: record_source
            data_type: varchar(255)

  - name: psa
    database: orcavault
    schema: psa
    tables:
      - name: event__sequence_run_state_change
        columns:
          - name: event_id
            data_type: varchar
          - name: event_time
            data_type: varchar
          - name: orcabus_id
            data_type: varchar
          - name: status
            data_type: varchar
          - name: instrument_run_id
            data_type: varchar
          - name: start_time
            data_type: varchar
          - name: end_time
            data_type: varchar
          - name: samplesheet_name
            data_type: varchar
          - name: load_datetime
            data_type: timestamptz
          - name: record_source
            data_type: varchar(255)

  - name: psa
    database: orcavault
    schema: psa
    tables:
      - name: event__sequence_run_library_linking_change
        columns:
          - name: event_id
            data_type: varchar
          - name: event_time
            data_type: varchar
          - name: orcabus_id
            data_type: varchar
          - name: instrument_run_id
            data_type: varchar
          - name: sequence_run_id
            data_type: varchar
          - name: timestamp
            data_type: varchar
          - name: libraries
            data_type: jsonb
          - name: load_datetime
            data_type: timestamptz
          - name: record_source
            data_type: varchar(255)

  - name: psa
    database: orcavault
    schema: psa
    tables:
      - name: event__workflow_run_state_change
        columns:
          - name: event_id
            data_type: varchar
          - name: event_time
            data_type: varchar
          - name: portal_run_id
            data_type: varchar
          - name: status
            data_type: varchar
          - name: state_timestamp
            data_type: varchar
          - name: workflow_name
            data_type: varchar
          - name: workflow_version
            data_type: varchar
          - name: workflow_run_name
            data_type: varchar
          - name: libraries
            data_type: jsonb
          - name: load_datetime
            data_type: timestamptz
          - name: record_source
            data_type: varchar(255)

  - name: psa
    database: orcavault
    schema: psa
    tables:
      - name: event__metadata_state_change_library
        columns:
          - name: event_id
            data_type: varchar
          - name: event_time
            data_type: varchar
          - name: orcabus_id
            data_type: varchar
          - name: action
            data_type: varchar
          - name: library_id
            data_type: varchar
          - name: phenotype
            data_type: varchar
          - name: workflow
            data_type: varchar
          - name: quality
            data_type: varchar
          - name: type
            data_type: varchar
          - name: assay
            data_type: varchar
          - name: coverage
            data_type: varchar
          - name: override_cycles
            data_type: varchar
          - name: sample_orcabus_id
            data_type: varchar
          - name: subject_orcabus_id
            data_type: varchar
          - name: load_datetime
            data_type: varchar
          - name: record_source
            data_type: varchar
