SELECT current_database();

-- create ods schema
CREATE SCHEMA IF NOT EXISTS ods AUTHORIZATION dev;
SET search_path TO ods;

SELECT current_schema();

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysis
(
    orcabus_id       varchar(26)  not null primary key,
    analysis_name    varchar(255) not null,
    analysis_version varchar(255) not null,
    description      varchar(255),
    status           varchar(255) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysis_contexts
(
    id                 bigint generated by default as identity primary key,
    analysis_id        varchar(26) not null,
    analysiscontext_id varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysis_workflows
(
    id          bigint generated by default as identity primary key,
    analysis_id varchar(26) not null,
    workflow_id varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysiscontext
(
    orcabus_id  varchar(26)  not null primary key,
    name        varchar(255) not null,
    usecase     varchar(255) not null,
    description varchar(255),
    status      varchar(255) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysisrun
(
    orcabus_id        varchar(26)  not null primary key,
    analysis_run_name varchar(255) not null,
    comment           varchar(255),
    analysis_id       varchar(26)
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysisrun_contexts
(
    id             bigint generated by default as identity primary key,
    analysisrun_id varchar(26) not null,
    runcontext_id  varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysisrun_libraries
(
    id             bigint generated by default as identity primary key,
    analysisrun_id varchar(26) not null,
    library_id     varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysisrun_readsets
(
    id             bigint generated by default as identity primary key,
    analysisrun_id varchar(26) not null,
    readset_id     varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_analysisrunstate
(
    orcabus_id      varchar(26)              not null primary key,
    status          varchar(255)             not null,
    timestamp       timestamp with time zone not null,
    comment         varchar(255),
    analysis_run_id varchar(26)              not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_library
(
    orcabus_id varchar(26)  not null primary key,
    library_id varchar(255) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_libraryassociation
(
    orcabus_id       varchar(26)              not null primary key,
    association_date timestamp with time zone not null,
    status           varchar(255)             not null,
    library_id       varchar(26)              not null,
    workflow_run_id  varchar(26)              not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_payload
(
    orcabus_id     varchar(26)  not null primary key,
    payload_ref_id varchar(255) not null unique,
    version        varchar(255) not null,
    data           jsonb        not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_readset
(
    orcabus_id         varchar(26)  not null primary key,
    rgid               varchar(255) not null,
    library_id         varchar(255) not null,
    library_orcabus_id varchar(255) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_runcontext
(
    orcabus_id  varchar(26)  not null primary key,
    name        varchar(255) not null,
    usecase     varchar(255) not null,
    description varchar(255),
    status      varchar(255) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_state
(
    orcabus_id      varchar(26)              not null primary key,
    status          varchar(255)             not null,
    timestamp       timestamp with time zone not null,
    comment         varchar(255),
    payload_id      varchar(26),
    workflow_run_id varchar(26)              not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_workflow
(
    orcabus_id                   varchar(26)  not null primary key,
    name                         varchar(255) not null,
    version                      varchar(255) not null,
    execution_engine             varchar(255) not null,
    execution_engine_pipeline_id varchar(255) not null,
    validation_state             varchar(255) not null,
    code_version                 varchar(255) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_workflowrun
(
    orcabus_id        varchar(26)  not null primary key,
    portal_run_id     varchar(255) not null unique,
    execution_id      varchar(255),
    workflow_run_name varchar(255),
    comment           varchar(255),
    analysis_run_id   varchar(26),
    workflow_id       varchar(26)
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_workflowrun_contexts
(
    id             bigint generated by default as identity primary key,
    workflowrun_id varchar(26) not null,
    runcontext_id  varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_workflowrun_readsets
(
    id             bigint generated by default as identity primary key,
    workflowrun_id varchar(26) not null,
    readset_id     varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.workflow_manager_workflowruncomment
(
    orcabus_id      varchar(26)              not null primary key,
    comment         text                     not null,
    created_at      timestamp with time zone not null,
    created_by      varchar(255)             not null,
    updated_at      timestamp with time zone not null,
    is_deleted      boolean                  not null,
    workflow_run_id varchar(26)              not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.sequence_run_manager_comment
(
    orcabus_id  varchar(26)              not null primary key,
    comment     text                     not null,
    target_id   varchar(26)              not null,
    created_at  timestamp with time zone not null,
    created_by  varchar(255)             not null,
    updated_at  timestamp with time zone not null,
    is_deleted  boolean                  not null,
    target_type varchar(255)             not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.sequence_run_manager_libraryassociation
(
    orcabus_id       varchar(26)              not null primary key,
    library_id       varchar(255)             not null,
    association_date timestamp with time zone not null,
    status           varchar(255)             not null,
    sequence_id      varchar(26)              not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.sequence_run_manager_samplesheet
(
    orcabus_id            varchar(26)              not null primary key,
    sample_sheet_name     varchar(255)             not null,
    association_status    varchar(255)             not null,
    association_timestamp timestamp with time zone not null,
    sample_sheet_content  jsonb,
    sequence_id           varchar(26)              not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.sequence_run_manager_sequence
(
    orcabus_id        varchar(26)  not null primary key,
    instrument_run_id varchar(255),
    run_volume_name   text,
    run_folder_path   text,
    run_data_uri      text,
    status            varchar(255),
    start_time        timestamp with time zone,
    end_time          timestamp with time zone,
    reagent_barcode   varchar(255),
    flowcell_barcode  varchar(255),
    sample_sheet_name varchar(255) not null,
    sequence_run_id   varchar(255) not null,
    sequence_run_name varchar(255),
    v1pre3_id         varchar(255),
    ica_project_id    varchar(255),
    api_url           text,
    experiment_name   varchar(255)
);

CREATE TABLE IF NOT EXISTS orcavault.ods.sequence_run_manager_state
(
    orcabus_id  varchar(26)              not null primary key,
    status      varchar(255)             not null,
    timestamp   timestamp with time zone not null,
    comment     varchar(255),
    sequence_id varchar(26)              not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_contact
(
    orcabus_id  varchar(26) not null primary key,
    contact_id  varchar unique,
    name        varchar,
    description varchar,
    email       varchar(254)
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_individual
(
    orcabus_id    varchar(26) not null primary key,
    individual_id varchar unique,
    source        varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_library
(
    orcabus_id         varchar(26) not null primary key,
    library_id         varchar unique,
    phenotype          varchar,
    workflow           varchar,
    quality            varchar,
    type               varchar,
    assay              varchar,
    coverage           double precision,
    sample_orcabus_id  varchar(26),
    subject_orcabus_id varchar(26),
    override_cycles    varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_libraryprojectlink
(
    id                 bigint generated by default as identity primary key,
    library_orcabus_id varchar(26) not null,
    project_orcabus_id varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_project
(
    orcabus_id  varchar(26) not null primary key,
    project_id  varchar unique,
    name        varchar,
    description varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_projectcontactlink
(
    id                 bigint generated by default as identity primary key,
    contact_orcabus_id varchar(26) not null,
    project_orcabus_id varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_sample
(
    orcabus_id         varchar(26) not null primary key,
    sample_id          varchar unique,
    external_sample_id varchar,
    source             varchar
);


CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_subject
(
    orcabus_id varchar(26) not null primary key,
    subject_id varchar unique
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_subjectindividuallink
(
    id                    bigint generated by default as identity primary key,
    individual_orcabus_id varchar(26) not null,
    subject_orcabus_id    varchar(26) not null
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicalcontact
(
    orcabus_id            varchar(26)              not null,
    contact_id            varchar,
    name                  varchar,
    description           varchar,
    email                 varchar(254),
    history_id            integer generated by default as identity primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicalindividual
(
    orcabus_id            varchar(26)              not null,
    individual_id         varchar,
    source                varchar,
    history_id            integer generated by default as identity primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicallibrary
(
    orcabus_id            varchar(26)              not null,
    library_id            varchar,
    phenotype             varchar,
    workflow              varchar,
    quality               varchar,
    type                  varchar,
    assay                 varchar,
    coverage              double precision,
    history_id            integer generated by default as identity primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    sample_orcabus_id     varchar(26),
    subject_orcabus_id    varchar(26),
    history_user_id       varchar,
    override_cycles       varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicallibraryprojectlink
(
    id                 bigint  not null,
    m2m_history_id     integer generated by default as identity primary key,
    history_id         integer not null,
    library_orcabus_id varchar(26),
    project_orcabus_id varchar(26)
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicalproject
(
    orcabus_id            varchar(26)              not null,
    project_id            varchar,
    name                  varchar,
    description           varchar,
    history_id            integer generated by default as identity primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicalprojectcontactlink
(
    id                 bigint  not null,
    m2m_history_id     integer generated by default as identity primary key,
    contact_orcabus_id varchar(26),
    history_id         integer not null,
    project_orcabus_id varchar(26)
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicalsample
(
    orcabus_id            varchar(26)              not null,
    sample_id             varchar,
    external_sample_id    varchar,
    source                varchar,
    history_id            integer generated by default as identity primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicalsubject
(
    orcabus_id            varchar(26)              not null,
    subject_id            varchar,
    history_id            integer generated by default as identity primary key,
    history_date          timestamp with time zone not null,
    history_change_reason varchar(100),
    history_type          varchar(1)               not null,
    history_user_id       varchar
);

CREATE TABLE IF NOT EXISTS orcavault.ods.metadata_manager_historicalsubjectindividuallink
(
    id                    bigint  not null,
    m2m_history_id        integer generated by default as identity primary key,
    history_id            integer not null,
    individual_orcabus_id varchar(26),
    subject_orcabus_id    varchar(26)
);

CREATE TYPE archive_status AS ENUM ('ArchiveAccess', 'DeepArchiveAccess');
CREATE TYPE crawl_status AS ENUM ('InProgress', 'Completed', 'Failed');
CREATE TYPE event_type AS ENUM ('Created', 'Deleted', 'Other');
CREATE TYPE reason AS ENUM ('CreatedPut', 'CreatedPost', 'CreatedCopy', 'CreatedCompleteMultipartUpload', 'Deleted', 'DeletedLifecycle', 'Restored', 'RestoreExpired', 'StorageClassChanged', 'Crawl', 'Unknown', 'CrawlRestored');
CREATE TYPE storage_class AS ENUM ('DeepArchive', 'Glacier', 'GlacierIr', 'IntelligentTiering', 'OnezoneIa', 'Outposts', 'ReducedRedundancy', 'Snow', 'Standard', 'StandardIa');

CREATE TABLE IF NOT EXISTS orcavault.ods.file_manager_s3_object
(
    s3_object_id            uuid                              not null primary key,
    event_type              event_type                        not null,
    bucket                  text                              not null,
    key                     text                              not null,
    version_id              text    default 'null'::text      not null,
    event_time              timestamp with time zone,
    size                    bigint,
    sha256                  text,
    last_modified_date      timestamp with time zone,
    e_tag                   text,
    storage_class           storage_class,
    sequencer               text,
    is_delete_marker        boolean default false             not null,
    number_duplicate_events bigint  default 0                 not null,
    attributes              jsonb,
    deleted_date            timestamp with time zone,
    deleted_sequencer       text,
    number_reordered        bigint  default 0                 not null,
    ingest_id               uuid,
    is_current_state        boolean default true              not null,
    reason                  reason  default 'Unknown'::reason not null,
    archive_status          archive_status,
    is_accessible           boolean
);
